
const types = {
    AVAILABILITY_FETCH_STARTED: 'AVAILABILITY_FETCH_STARTED',
    AVAILABILITY_FETCH_SUCCESS: 'AVAILABILITY_FETCH_SUCCESS',
    AVAILABILITY_FETCH_FAILURE: 'AVAILABILITY_FETCH_FAILURE',
    
    BOOKINGS_FETCH_STARTED: 'BOOKINGS_FETCH_STARTED',
    BOOKINGS_FETCH_SUCCESS: 'BOOKINGS_FETCH_SUCCESS',
    BOOKINGS_FETCH_FAILURE: 'BOOKINGS_FETCH_FAILURE',
    
    BOOKTIME_STARTED: 'BOOKTIME_STARTED',
    BOOKTIME_SUCCESS: 'BOOKTIME_SUCCESS',
    BOOKTIME_FAILURE: 'BOOKTIME_FAILURE',
    
    TODAY_FETCH_STARTED: 'TODAY_FETCH_STARTED',
    TODAY_FETCH_SUCCESS: 'TODAY_FETCH_SUCCESS',
    TODAY_FETCH_FAILURE: 'TODAY_FETCH_FAILURE',
    
    UPDATE_STUDENT_NAME: 'UPDATE_STUDENT_NAME',
};

export default types;